line-length = 100

[lint]
select = [
    "E",    # pycodestyle
    "F",    # Pyflakes
    "UP",    # pyupgrade
    "B",    # flake8-bugbear
    "I",    # isort
]

[format]
indent-style = "space"
quote-style = "double"
docstring-code-format = true
docstring-code-line-length = 50